website/views.py
from flask import Blueprint, render_template, request, jsonify, flash, redirect, url_for
from flask_login import login_required, current_user
import json

views = Blueprint('views', __name__)


@views.route('/')
@login_required
def home():
    return render_template("home.html", user=current_user)


@views.route('/notification', methods=['GET', 'POST'])
@login_required
def notification():
    return render_template("notification.html", user=current_user)


@views.route('/delete-note', methods=['POST'])
def delete_note():
    try:
        from .models import Note
        note = json.loads(request.data)
        noteId = note['noteId']
        note = Note.query.get(noteId)
        if note:
            if note.user_id == current_user.id:
                from . import db
                db.session.delete(note)
                db.session.commit()
                flash('Notification Deleted', category='success')
            else:
                flash('Notification couldn\'t be deleted', category='error')

        return jsonify({})
    except Exception as e:
        flash("Something went wrong !", category="error")
        print(e)


@views.route('/plumbers', methods=['GET', 'POST'])
@login_required
def plumbers():
    try:
        from .models import Plumbers
        plumbers = Plumbers.query.all()
        return render_template("plumbers_page.html", user=current_user, plumbers=plumbers)
    except Exception as e:
        flash("Something went wrong !", category="error")
        print(e)


@views.route('/view-profile', methods=['GET', 'POST'])
@login_required
def view_profile():
    return render_template("profile_page.html", user=current_user)


@views.route('/edit-profile-page', methods=['GET', 'POST'])
@login_required
def edit_profile_page():
    try:
        if request.method == 'POST':
            email = request.form.get('email')
            fullname = request.form.get('name')
            city = request.form.get('city')
            address = request.form.get('address')
            user_id = current_user.id
            current_user_email = current_user.email

            from .models import User
            user = User.query.filter_by(email=email).first()
            if user and current_user_email != email:
                flash('Email is already taken, try another email.', category='error')
            elif len(fullname) < 3:
                flash('Full name must be greater than 2 characters.', category='error')
            elif len(email) < 4:
                flash('Email must be greater than 3 characters.', category='error')
            elif len(address) < 10:
                flash('Address is too short.', category='error')
            else:
                from .models import User
                edit_user = User.query.get(user_id)

                from . import db

                edit_user.fullname = fullname
                edit_user.email = email
                edit_user.address = address
                edit_user.city = city

                db.session.commit()
                flash('Profile Updated Successfully.', category='success')
                return redirect(url_for('views.view_profile'))
    except Exception as e:
        print(e)
        flash('Something went wrong.', category='error')
    return render_template("edit_profile_page.html", user=current_user)


@views.route('/view-plumber-details/<int:record_id>', methods=['GET', 'POST'])
@login_required
def view_plumber_details(record_id):
    try:
        from .models import Plumbers, WorkEngine, HiredUser
        selected_plumber = Plumbers.query.get(record_id)
        name = selected_plumber.name
        plumber_work = selected_plumber.work
        loaded_engine = WorkEngine.recommendations
        h_user = HiredUser.query.filter_by(name=name).first()
        if h_user:
            status = 'On A Hire'
        else:
            status = 'Available'

        id_1 = loaded_engine(plumber_work)[0][0]
        id_2 = loaded_engine(plumber_work)[0][1]
        id_3 = loaded_engine(plumber_work)[0][2]
        id_4 = loaded_engine(plumber_work)[0][3]
        id_5 = loaded_engine(plumber_work)[0][4]
        id_6 = loaded_engine(plumber_work)[0][5]

        recommended_plumber_1 = Plumbers.query.get(id_1)
        recommended_plumber_2 = Plumbers.query.get(id_2)
        recommended_plumber_3 = Plumbers.query.get(id_3)
        recommended_plumber_4 = Plumbers.query.get(id_4)
        recommended_plumber_5 = Plumbers.query.get(id_5)
        recommended_plumber_6 = Plumbers.query.get(id_6)

        return render_template("selected_plumber.html", user=current_user, plumber=selected_plumber,
                               rec_plumber_1=recommended_plumber_1, rec_plumber_2=recommended_plumber_2,
                               rec_plumber_3=recommended_plumber_3, rec_plumber_4=recommended_plumber_4,
                               rec_plumber_5=recommended_plumber_5, rec_plumber_6=recommended_plumber_6, status=status)
    except Exception as e:
        flash("Something went wrong !", category="error")
        print(e)


@views.route('/hire-me/<int:record_id>', methods=['GET', 'POST'])
@login_required
def hire_me(record_id):
    try:
        from .models import Plumbers, HiredUser, Note
        import datetime
        now = datetime.datetime.now()
        hired_plumber = Plumbers.query.get(record_id)

        name = hired_plumber.name
        telephone = hired_plumber.telephone
        work = hired_plumber.work
        status = 'On The Way'
        plumber_id = hired_plumber.id
        user_id = current_user.id
        data = name + ' is hired, he will be on the way.'

        from .models import HiredUser, User
        h_user = HiredUser.query.filter_by(name=name).first()
        user = HiredUser.query.filter_by(user_id=user_id).first()
        user_city = current_user.city
        plumber_city = hired_plumber.city_of_work
        if h_user:
            flash(name + ' is already on hire.', category='error')
            return redirect(url_for("views.plumbers"))
        elif user:
            flash('A plumber has already been hired by you. Once the current hire is completed, you can hire more.',
                  category='error')
            return redirect(url_for("views.current_hiring"))
        elif user_city != plumber_city:
            flash(name + ' is currently working in ' + plumber_city + ', you can only hire plumbers from ' + user_city +
                  '.',
                  category='error')
            return redirect(url_for("views.plumbers"))
        else:
            from . import db
            new_hired_plumber = HiredUser(name=name, telephone=telephone, work=work, status=status, user_id=user_id,
                                          plumber_id=plumber_id)
            db.session.add(new_hired_plumber)
            db.session.commit()
            notifications = Note(data=data, date=now, user_id=user_id)
            db.session.add(notifications)
            db.session.commit()
            flash(name + ' is hired successfully.', category='success')
            return redirect(url_for("views.current_hiring"))
    except Exception as e:
        print(e)
        flash("Something went wrong !", category="error")
        return redirect(url_for("views.current_hiring"))


@views.route('/current-hiring', methods=['GET', 'POST'])
@login_required
def current_hiring():
    try:
        from .models import HiredUser
        current_hired_user = HiredUser.query.all()
        return render_template("current_hiring.html", user=current_user, hired=current_hired_user)

    except Exception as e:
        flash("Something went wrong !", category="error")
        print(e)


@views.route('/details-of-hired-plumber/<int:record_id>', methods=['GET', 'POST'])
@login_required
def view_hired_plumber_details(record_id):
    try:
        from .models import Plumbers, HiredUser

        status_of_hired_plumber = HiredUser.query.get(record_id)
        plumber_id = status_of_hired_plumber.plumber_id

        details_of_hired_plumber = Plumbers.query.get(plumber_id)
        return render_template("view_details_hired_plumber.html", user=current_user, plumber=details_of_hired_plumber,
                               hired_plumber=status_of_hired_plumber)
    except Exception as e:
        flash("Something went wrong !", category="error")
        print(e)


@views.route('/update-arrived/<int:record_id>', methods=['GET', 'POST'])
@login_required
def update_arrived(record_id):
    try:
        from .models import HiredUser, Note
        details_of_hired_plumber = HiredUser.query.get(record_id)
        name = details_of_hired_plumber.name
        status = 'Arrived'
        data = name + ' has arrived at your location. Make sure to click work completed once the work is done'
        import datetime
        now = datetime.datetime.now()
        user_id = current_user.id

        from . import db
        details_of_hired_plumber.status = status
        db.session.commit()

        notifications = Note(data=data, date=now, user_id=user_id)
        db.session.add(notifications)
        db.session.commit()

        flash(name + " has arrived at your location.",
              category="success")
        flash("Make sure to click work completed button once the work is done.",
              category="success")

    except Exception as e:
        flash("Something went wrong !", category="error")
        print(e)

    return redirect(url_for("views.current_hiring"))


@views.route('/work-completed/<int:record_id>', methods=['GET', 'POST'])
@login_required
def work_completed(record_id):
    try:
        from .models import HiredUser, HiredHistory, Note, UserInterest
        details_of_hired_plumber = HiredUser.query.get(record_id)

        name = details_of_hired_plumber.name
        telephone = details_of_hired_plumber.telephone
        work = details_of_hired_plumber.work
        status = 'Completed'
        user_id = details_of_hired_plumber.user_id

website/templates/city_plumbers_recomendation.html
{% extends 'base.html' %}
{% block title %}Plumbers{% endblock %}
{% block content %}



<div align="center" class="card-header text-dark  column">
  <h1><b>Plumbers In {{ plumber_1.city_of_work }}</b></h1>
 <a href="{{ url_for('views.plumbers') }}" class="btn btn-warning" style="border-radius: 15px">View All Plumbers</a>
</div>

  <br>


<!---->
  <div align="center">

    <div align="center" class="row row-cols-1 row-cols-md-3 g-4">


<!--    1st recommendation  -->
  <div class="col">
    <div class="card bg-secondary text-white h-100" style="width: 360px; border-radius: 30px">


      <h5 class="card-header bg-dark" style="border-radius: 30px"><b>{{ plumber_1.name }}</b></h5>
      {% set plumber_id=plumber_1.id %}
  <div class="card-body">
    <h5 class="card-title">{{ plumber_1.work }}</h5>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Working City :</b> {{ plumber_1.city_of_work }}</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Experience :</b> {{ plumber_1.years_of_experience }} years</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Qualification :</b> NVQ {{ plumber_1.nvq_level }}</p>

      <div class="card-footer bg-transparent border-white-50">
        <div align="center">
          <a href="{{ url_for('views.view_plumber_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">Hire Me</a>
        </div>
      </div>


  </div>


    </div>

    </div>
<!--   end of 1st recommendation   -->

<!---->

<!--    2nd recommendation  -->
  <div class="col">
    <div class="card bg-secondary text-white h-100" style="width: 360px; border-radius: 30px">


      <h5 class="card-header bg-dark" style="border-radius: 30px"><b>{{ plumber_2.name }}</b></h5>
      {% set plumber_id=plumber_2.id %}
  <div class="card-body">
    <h5 class="card-title">{{ plumber_2.work }}</h5>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Working City :</b> {{ plumber_2.city_of_work }}</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Experience :</b> {{ plumber_2.years_of_experience }} years</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Qualification :</b> NVQ {{ plumber_2.nvq_level }}</p>

      <div class="card-footer bg-transparent border-white-50">
        <div align="center">
          <a href="{{ url_for('views.view_plumber_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">Hire Me</a>
        </div>
      </div>


  </div>


    </div>

    </div>
<!--   end of 2nd recommendation   -->

<!---->

<!--    3rd recommendation  -->
  <div class="col">
    <div class="card bg-secondary text-white h-100" style="width: 360px; border-radius: 30px">


      <h5 class="card-header bg-dark" style="border-radius: 30px"><b>{{ plumber_3.name }}</b></h5>
      {% set plumber_id=plumber_3.id %}
  <div class="card-body">
    <h5 class="card-title">{{ plumber_3.work }}</h5>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Working City :</b> {{ plumber_3.city_of_work }}</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Experience :</b> {{ plumber_3.years_of_experience }} years</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Qualification :</b> NVQ {{ plumber_3.nvq_level }}</p>

      <div class="card-footer bg-transparent border-white-50">
        <div align="center">
          <a href="{{ url_for('views.view_plumber_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">Hire Me</a>
        </div>
      </div>


  </div>


    </div>

    </div>
<!--   end of 3rd recommendation   -->

<!---->

 <!--    4th recommendation  -->
  <div class="col">
    <div class="card bg-secondary text-white h-100" style="width: 360px; border-radius: 30px">


      <h5 class="card-header bg-dark" style="border-radius: 30px"><b>{{ plumber_4.name }}</b></h5>
      {% set plumber_id=plumber_4.id %}
  <div class="card-body">
    <h5 class="card-title">{{ plumber_4.work }}</h5>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Working City :</b> {{ plumber_4.city_of_work }}</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Experience :</b> {{ plumber_4.years_of_experience }} years</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Qualification :</b> NVQ {{ plumber_4.nvq_level }}</p>

      <div class="card-footer bg-transparent border-white-50">
        <div align="center">
          <a href="{{ url_for('views.view_plumber_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">Hire Me</a>
        </div>
      </div>


  </div>


    </div>

    </div>
<!--   end of 4th recommendation   -->

<!---->

  <!--    5th recommendation  -->
  <div class="col">
    <div class="card bg-secondary text-white h-100" style="width: 360px; border-radius: 30px">


      <h5 class="card-header bg-dark" style="border-radius: 30px"><b>{{ plumber_5.name }}</b></h5>
      {% set plumber_id=plumber_5.id %}
  <div class="card-body">
    <h5 class="card-title">{{ plumber_5.work }}</h5>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Working City :</b> {{ plumber_5.city_of_work }}</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Experience :</b> {{ plumber_5.years_of_experience }} years</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Qualification :</b> NVQ {{ plumber_5.nvq_level }}</p>

      <div class="card-footer bg-transparent border-white-50">
        <div align="center">
          <a href="{{ url_for('views.view_plumber_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">Hire Me</a>
        </div>
      </div>


  </div>


    </div>

    </div>
<!--   end of 5th recommendation   -->

 <!---->

<!--    6th recommendation  -->
  <div class="col">
    <div class="card bg-secondary text-white h-100" style="width: 360px; border-radius: 30px">


      <h5 class="card-header bg-dark" style="border-radius: 30px"><b>{{ plumber_6.name }}</b></h5>
      {% set plumber_id=plumber_6.id %}
  <div class="card-body">
    <h5 class="card-title">{{ plumber_6.work }}</h5>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Working City :</b> {{ plumber_6.city_of_work }}</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Experience :</b> {{ plumber_6.years_of_experience }} years</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Qualification :</b> NVQ {{ plumber_6.nvq_level }}</p>

      <div class="card-footer bg-transparent border-white-50">
        <div align="center">
          <a href="{{ url_for('views.view_plumber_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">Hire Me</a>
        </div>
      </div>


  </div>


    </div>

    </div>
<!--   end of 6th recommendation   -->

<!---->

<!--    7th recommendation  -->
  <div class="col">
    <div class="card bg-secondary text-white h-100" style="width: 360px; border-radius: 30px">


      <h5 class="card-header bg-dark" style="border-radius: 30px"><b>{{ plumber_7.name }}</b></h5>
      {% set plumber_id=plumber_7.id %}
  <div class="card-body">
    <h5 class="card-title">{{ plumber_7.work }}</h5>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Working City :</b> {{ plumber_7.city_of_work }}</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Experience :</b> {{ plumber_7.years_of_experience }} years</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Qualification :</b> NVQ {{ plumber_7.nvq_level }}</p>

      <div class="card-footer bg-transparent border-white-50">
        <div align="center">
          <a href="{{ url_for('views.view_plumber_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">Hire Me</a>
        </div>
      </div>


  </div>


    </div>

    </div>
<!--   end of 7th recommendation   -->

<!---->

<!--    8th recommendation  -->
  <div class="col">
    <div class="card bg-secondary text-white h-100" style="width: 360px; border-radius: 30px">


      <h5 class="card-header bg-dark" style="border-radius: 30px"><b>{{ plumber_8.name }}</b></h5>
      {% set plumber_id=plumber_8.id %}
  <div class="card-body">
    <h5 class="card-title">{{ plumber_8.work }}</h5>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Working City :</b> {{ plumber_8.city_of_work }}</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Experience :</b> {{ plumber_8.years_of_experience }} years</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Qualification :</b> NVQ {{ plumber_8.nvq_level }}</p>

      <div class="card-footer bg-transparent border-white-50">
        <div align="center">
          <a href="{{ url_for('views.view_plumber_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">Hire Me</a>
        </div>
      </div>


  </div>


    </div>

    </div>
<!--   end of 8th recommendation   -->

 <!---->

<!--    9th recommendation  -->
  <div class="col">
    <div class="card bg-secondary text-white h-100" style="width: 360px; border-radius: 30px">


      <h5 class="card-header bg-dark" style="border-radius: 30px"><b>{{ plumber_9.name }}</b></h5>
      {% set plumber_id=plumber_9.id %}
  <div class="card-body">
    <h5 class="card-title">{{ plumber_9.work }}</h5>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Working City :</b> {{ plumber_9.city_of_work }}</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Experience :</b> {{ plumber_9.years_of_experience }} years</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Qualification :</b> NVQ {{ plumber_9.nvq_level }}</p>

      <div class="card-footer bg-transparent border-white-50">
        <div align="center">
          <a href="{{ url_for('views.view_plumber_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">Hire Me</a>
        </div>
      </div>


  </div>


    </div>

    </div>
<!--   end of 9th recommendation   -->

 <!---->

<!--    10th recommendation  -->
  <div class="col">
    <div class="card bg-secondary text-white h-100" style="width: 360px; border-radius: 30px">


      <h5 class="card-header bg-dark" style="border-radius: 30px"><b>{{ plumber_10.name }}</b></h5>
      {% set plumber_id=plumber_10.id %}
  <div class="card-body">
    <h5 class="card-title">{{ plumber_10.work }}</h5>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Working City :</b> {{ plumber_10.city_of_work }}</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Experience :</b> {{ plumber_10.years_of_experience }} years</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Qualification :</b> NVQ {{ plumber_10.nvq_level }}</p>

      <div class="card-footer bg-transparent border-white-50">
        <div align="center">
          <a href="{{ url_for('views.view_plumber_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">Hire Me</a>
        </div>
      </div>


  </div>


    </div>

    </div>
<!--   end of 10th recommendation   -->

  </div>

  </div>







{% endblock %}

website/templates/completed_hiring.html
{% extends 'base.html' %}
{% block title %}Hiring History{% endblock %}
{% block content %}

<div align="center" style="background-color: #ECFFDC">

     <h1 class="card-header text-white bg-secondary">Your Hired History</h1>

  <br>
<div align="center">

    <div align="center" class="row row-cols-1 row-cols-md-3 g-4">



      {% for plumber in hired|sort(attribute='id', reverse = True) %}
    {% if plumber.user_id==user.id  %}
      <div class="col">


        <div class="card-group border-dark"  style="width: 320px;">


  <div class="card" style="border-radius: 20px; border-color: yellowgreen">

    <div align="center">
          <img src="https://1eozh3q70fp16zmk31vlucb1-wpengine.netdna-ssl.com/wp-content/uploads/2018/04/Six-Major-Reasons-Why-You-Should-Hire-a-Professional-Plumber-in-Georgetown-SC-1024x683.jpg" style="width: 300px; height: 200px; padding-top: 5px; border-radius: 15px" class="card-img-top" alt="...">
    </div>
    {% set plumber_id=plumber.id %}
    <div class="card-body">
      <h4 class="card-header text-white bg-dark" style="border-radius: 25px">{{ plumber.name }}</h4>
      <h5 class="card-text"><b>{{ plumber.work }}</b></h5>
        </div>

    <div class="card-footer row-cols-1">
        <p class="card-text" style="color: red; font-family: 'Helvetica', sans-serif; font-weight: lighter; font-size: 25px">{{ plumber.status }}</p>
    </div>
      <div class="card-footer row-cols-2">
      <a href="{{ url_for('views.view_hired_plumber_history_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">View Details</a>
    </div>

  </div>
    </div>



      </div>

    {% endif %}
    {% endfor %}




    </div>
  </div>


<br>
</div>


{% endblock %}

website/templates/current_hiring.html
{% extends 'base.html' %}
{% block title %}Current Hiring{% endblock %}
{% block content %}

<div align="center" style="background-color: #ECFFDC">

     <h1 class="card-header text-white bg-secondary">Your Current Hiring</h1>

  <br>

  <div class="card-group border-dark"  style="width: 320px;">

{% for plumber in hired %}
    {% if plumber.user_id==user.id  %}
  <div class="card shadow-lg" style="border-radius: 20px; border-color: yellowgreen">

    <div align="center">
          <img src="https://www.proxims-barcelona.com/wp-content/uploads/2021/06/plumber.jpg" style="width: 300px; height: 200px; padding-top: 5px; border-radius: 15px" class="card-img-top" alt="...">
    </div>

    <div class="card-body">
      <h5 class="card-header text-white bg-dark" style="border-radius: 25px">{{ plumber.name }}</h5>
      <h6 class="card-text"><b>{{ plumber.work }}</b></h6>
      <p class="card-text" style="color: red; font-family: 'Helvetica', sans-serif; font-weight: lighter; font-size: 25px">{{ plumber.status }}</p>
    </div>
    {% set plumber_id=plumber.id %}
    <div class="card-footer row-cols-1">
      <a href="{{ url_for('views.view_hired_plumber_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">View Details</a>
    </div>
    {% if plumber.status=='On The Way' %}
    <div class="card-footer row-cols-2">
      <a href="{{url_for('views.update_arrived', record_id = plumber_id )}}" class="btn btn-warning" style="border-radius: 15px;">Plumber Arrived</a>
    </div>
    {% else %}
    <div class="card-footer row-cols-2">
      <a href="{{url_for('views.work_completed', record_id = plumber_id )}}" class="btn btn-warning" style="border-radius: 15px">Work Completed</a>
    </div>
    {%endif%}
  </div>
    {% endif %}
    {% endfor %}


</div>
<br>
</div>


{% endblock %}

website/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}

<form method="post">
    <h3 align="center"></h3>
    <div class="form-group">

        <h2 style="padding-left: 630px">Login</h2>

        <div align="center">


            <br>


        <label for="email">Email Address</label>
        <input
            type="email"
            class="form-control"
            id="email"
            name="email"
            placeholder="Enter your email address"
            style="width: 300px"
            required
        />

            <label for="password">Password</label>
        <input
            type="password"
            class="form-control"
            id="password"
            name="password"
            placeholder="Enter your password"
            style="width: 300px"
            required
        />


            <br>
            <button class="btn btn-primary">Login</button>

        </div>


    </div>
</form>


{% endblock %}

website/templates/plumbers_page.html
{% extends 'base.html' %}
{% block title %}Plumbers{% endblock %}
{% block content %}



<div align="center" class="card-header text-dark  column">
  <h1><b>Plumbers</b></h1>
 <a href="{{ url_for('views.recommend_based_on_city') }}" class="btn btn-warning" style="border-radius: 15px">Recommend Based On My City</a>
 <a href="{{ url_for('views.recommend_based_on_interest') }}" class="btn btn-warning" style="border-radius: 15px">Recommend Based On My Interest</a>
</div>

  <br>


<!---->
  <div align="center">

    <div align="center" class="row row-cols-1 row-cols-md-3 g-4">

{% for plumber in plumbers %}
  <div class="col">
    <div class="card bg-secondary text-white h-100 shadow-lg" style="width: 360px; border-radius: 30px">

<!--      -->
      <h5 class="card-header bg-dark" style="border-radius: 30px"><b>{{ plumber.name }}</b></h5>
      {% set plumber_id=plumber.id %}
  <div class="card-body">
    <h5 class="card-title">{{ plumber.work }}</h5>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Working City :</b> {{ plumber.city_of_work }}</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Experience :</b> {{ plumber.years_of_experience }} years</p>
    <p class="card-text text-white-50 bg-dark" style="border-radius: 15px"><b>Qualification :</b> NVQ {{ plumber.nvq_level }}</p>

      <div class="card-footer bg-transparent border-white-50">
        <div align="center">
          <a href="{{ url_for('views.view_plumber_details', record_id = plumber_id) }}" class="btn btn-warning" style="border-radius: 15px">Hire Me</a>
        </div>
      </div>


  </div>
<!--      -->

    </div>

    </div>

  {% endfor %}


  </div>

  </div>







{% endblock %}